#!/bin/sh

set -e

echo "Running cargo fmt --all --check"
cargo fmt --all --check

echo "Running cargo check --locked"
cargo check --locked

echo "Running cargo clippy --locked --all-targets --all-features -- -D warnings"
cargo clippy --locked --all-targets --all-features -- -D warnings
